/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#e9ddff',
        'on-tertiary-fixed': '#002113',
        'primary-fixed': '#dbe1ff',
        'surface-container': '#e5eeff',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        'on-background': '#0b1c30',
        'surface-dim': '#cbdbf5',
        'on-secondary': '#ffffff',
        'secondary-container': '#8455ef',
        'error-container': '#ffdad6',
        'primary-container': '#2563eb',
        'inverse-primary': '#b4c5ff',
        'on-primary-container': '#eeefff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'tertiary-fixed': '#6ffbbe',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        background: '#f8f9ff',
        outline: '#737686',
        primary: '#004ac6',
        tertiary: '#006242',
        'tertiary-container': '#007d55',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#0053db',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed-variant': '#003ea8',
        'on-primary-fixed': '#00174b',
        'inverse-surface': '#213145',
        'on-secondary-container': '#fffbff',
        surface: '#f8f9ff',
        'on-tertiary-fixed-variant': '#005236',
        'on-secondary-fixed': '#23005c',
        'surface-variant': '#d3e4fe',
        'surface-container-low': '#eff4ff',
        'on-surface': '#0b1c30',
        'on-secondary-fixed-variant': '#5516be',
        'secondary-fixed-dim': '#d0bcff',
        'tertiary-fixed-dim': '#4edea3',
        secondary: '#6b38d4',
        'surface-bright': '#f8f9ff',
        'on-error': '#ffffff',
        'on-tertiary-container': '#bdffdb',
        'inverse-on-surface': '#eaf1ff',
        'on-surface-variant': '#434655',
        'outline-variant': '#c3c6d7',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'stack-lg': '24px',
        'stack-md': '16px',
        unit: '4px',
        'stack-sm': '8px',
        'gutter-mobile': '12px',
      },
      fontFamily: {
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Be Vietnam Pro"', 'sans-serif'],
        'body-md': ['"Be Vietnam Pro"', 'sans-serif'],
        'body-sm': ['"Be Vietnam Pro"', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'translation-text': ['"Be Vietnam Pro"', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '500' }],
        'translation-text': ['14px', { lineHeight: '20px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}